/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.presciense.poltergeist;

public class consumer_clientJNI {
  public final static native long init_ihd(String jarg1, JavaCallback jarg2, short jarg4);
  public final static native long init_mobile(String jarg1, String jarg2, String jarg3, JavaCallback jarg4, short jarg6);
  public final static native void connect_lan(long jarg1, String jarg2, String jarg3);
  public final static native void connect_oort(long jarg1, String jarg2);
  public final static native void sync_all_available_devices(long jarg1);
  public final static native void teardown(long jarg1);
  public final static native void permit_join(long jarg1, short jarg2);
  public final static native void form_ha_network(long jarg1);
  public final static native void join_se_network(long jarg1);
  public final static native void on_off_turn_on(long jarg1, String jarg2, short jarg3);
  public final static native void on_off_turn_off(long jarg1, String jarg2, short jarg3);
  public final static native void on_off_toggle(long jarg1, String jarg2, short jarg3);
}
