/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.presciense.poltergeist;

public class SWIGTYPE_p_Client {
  private transient long swigCPtr;

  protected SWIGTYPE_p_Client(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_Client() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

