general:
  error: An error occurred, please try again
  confirm_action:
    message: Are you sure you want to %(action)s?
    enable: enable
    disable: disable
  notice: Notice
  confirm: Confirm
  cancel: Cancel
  close: Close
  retry: Retry
  update: Update %(property)s
  change_to: Change to %(property)s

menu:
  no_network: No Network
  online: Online
  offline: Offline
  connected: Connected
  disconnected: Disconnected
  new: NEW

phone:
  title: Phone
  call_help: Select number to call
  cancel_call: Cancel
  voip_call: Call via app
  carrier_call: Call via mobile carrier
  calling: Calling...
  connected: Connected...
  mute: Mute
  speaker: Speaker

network:
  title: My Network
  adsl: ADSL
  3g: 3G
  wifi: Station WiFi
  guest_wifi: Guest WiFi
  phone: Phone
  wired: Wired
  devices:
    zero: No Devices
    one: 1 Device
    other: "%(count)s Devices"
  lines:
    zero: No Lines
    one: 1 Line
    other: "%(count)s Lines"

schedule:
  title: Schedule

support:
  title: Info & Support
  phone_status: Phone Status
  online: Online
  offline: Offline
  speed_test: Speed Test

diagnostics:
  title: Diagnostics
  results: Results
  no_results: No results, please run diagnostics
  running: Running diagnostics utility...
  run: Run Diagnostics
  result:
    code_8101: No DSL link detected.
    code_8102: DSL link is not stable, more than 3 times cuts in one day.
    code_8103: DSL link is not good, too many CRC errors.
    code_8104: No Fibre link.
    code_8105: Can't ping through gateway.
    code_8106: DNS lookup failed.
    code_8107: Up link congested.
    code_8108: No traffic from down link.
    code_8109: Telephone is not active.
    code_8110: Telephone registration failed.
    code_8111: WiFi authentication failed, probably password is not right.
    code_8112: WiFi is not good.
    code_8113: LAN1 link maybe broken, no packets received.
    code_8114: LAN1 link maybe congested, drop too many packets.
    code_8115: LAN2 link maybe broken, no packets received.
    code_8116: LAN2 link maybe congested, drop too many packets.
    code_8117: LAN3 link maybe broken, no packets received.
    code_8118: LAN3 link maybe congested, drop too many packets.
    code_8119: LAN4 link maybe broken, no packets received.
    code_8120: LAN4 link maybe congested, drop too many packets.
    code_8121: Can't connect to ACS server last time.
    code_8122: Free memory is too low.
    code_8123: Current CPU utilization is too high, more than 80% has been taken up.
    code_8124: No UMTS link detected.
    code_8200: No error has been detected.

feedback:
  title: Feedback

setup:
  title: Setup
  description: Setting up secure link...

signin:
  title: Sign In
  description: Please sign in or create an account with your preferred provider.
  facebook: Sign in with Facebook
  vk: Sign in with VKontakte
  google: Sign in with Google
  error: Unable to sign in - please try again

settings:
  title: Settings
  router:
    title: Router Settings
    remoteaccess: Remote Access
    description: |
      When enabled, you can manage your router and change configuration when
      you're away from home or connected to another network.
    selection: |
      You have access to more than one router, switch to another here
    secondaryusers: |
      Requests to access your routers
    returnhometoallow: Requires LAN
    approve: Approve
    reject: Reject
    change: Switch to
  notifications:
    title: Notifications
    description:  |
      Choose which events you would like to receive a push notification for,
      these settings are specific to this device.
    incomingcall: Incoming Calls
    missedcall: Missed Calls
    wpsfinished: WPS Finished
    newdeviceconnected: New Device Connection

wifi:
  title: Station WiFi
  enabled: Enabled
  disabled: Disabled
  pairing: Pairing
  enable: Enable
  disable: Disable
  pair: Pairing Mode
  security: Security
  no_password: No Password
  channel:
    title: Channel
    auto: auto
    manual: manual
    contention: View Contention
  guest_wifi:
    title: Guest WiFi
    description: |
      Creates a separate secured network that provides internet access to
      wireless devices for your guests.
  hotspot:
    title: WiFi Hotspot
    description: |
      Add your Station to Fon's global WiFi network that provides WiFi access
      to millions of hotspots all around the world.

my_vodafone:
  title: My Vodafone
  open: Open
  bills:
    title: Phone Bills
    description: |
      Enter My Vodafone to verify your subscribed offer, your bills,
      their due date and much more...
  line:
    title: Line Activation Status
    description: |
      If you are waiting for your line activation, you can check the
      state of progress through My Vodafone.
  itunes: id370901726
  google_play: com.myvodafoneapp

camera:
  title: Home Camera
  description: |
    Monitor your home with HD video streaming right to your
    VEON Smart Box app. We'll deliver your new camera to your
    door and setup is quick and easy.
  buy: Buy Now

intro:
  retry: Continue
  help:
    title: Help
    no_wifi:
      title: Unable to find your WiFi connection.
      description: |
        We were unable to find your Vodafone router on your WiFi network,
        please try the following steps to resolve:
      try0:
        suggest: |
          1. Check that the router is plugged in to the mains, and turn
          the router on by pressing the round 'ON/OFF' button on the back.
        confirm: |
          A red-light should be visible under the router. Please wait around
          one minute, and select 'Continue' below.
      try1:
        suggest: |
          2. Check that the router is powered on, ensure that the 'ON/OFF'
          switch at the back of the router is pressed in.
        confirm: |
          A red-light should be visible under the router. Please wait around
          one minute, and select 'Continue' below.
      try2:
        suggest: |
          3. Make sure your are connected to the WiFi network of the router.
          The name is shown on the back of the router and should be the same
          on your phone or tablet (assuming you haven't changed the network
          name from the default).
        confirm: |
          Your phone or tablet should be connected to the correct WiFi network.
          Please wait around one minute, and select 'Continue' below.
    no_internet:
      title: Unable to connect to internet.
      description: |
        We were unable to connect to the internet, please try the following
        steps to resolve:
      try0:
        suggest: |
          1. Check that the router is connected to the phone line, as shown
          in the picture below.
        confirm: |
          Please wait for around one minute, and select 'Continue' below.
      try1:
        suggest: |
          2. Check that your line is active in the 'My Vodafone' app.
        confirm: |
          Once confirmed select 'Continue' below.

awaitingapproval:
  title: Awaiting approval from owner
  description: |
    The owner has been notified of your request to access to this router. If you are approved then you will be granted access.

secondaryapplication:
  title: Choose a router
  description: |
    This router belongs to someone else, you can request to use it
  applyitem: Station
  apply: Apply
  resend: Resend
